import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { PASSWORD_MIN_LENGTH } from '../lib/authHelpers'
import { useAuth } from '../lib/auth'
import { SignOutButton } from '../components/teacher/AuthStatus'
export default function TeacherResetPasswordPage() {
  const { loading, recovery, callbackError, session, error: authError, resetPassword } = useAuth(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [pending, setPending] = useState(false); const [message, setMessage] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); if (password.length < PASSWORD_MIN_LENGTH) return setMessage(`Use at least ${PASSWORD_MIN_LENGTH} characters.`); if (password !== confirm) return setMessage('Passwords do not match.'); setPending(true); try { await resetPassword(password); setMessage('Your password has been updated. You can sign in with it now.'); window.setTimeout(() => navigate('/teacher/login', { replace: true }), 900) } catch (failure) { setMessage(failure instanceof Error ? failure.message : 'We couldn’t update your password. Please try again.') } finally { setPending(false) } }
  if (loading) return <p role="status">Checking recovery link…</p>
  if (!recovery || !session || callbackError || authError) return <section className="mx-auto max-w-lg rounded-2xl bg-white p-8"><h1 className="text-3xl font-extrabold">Password reset link unavailable</h1><p className="mt-4" role="alert">This link is invalid, expired, or already used. Request a new one to continue.</p><Link className="mt-5 inline-block font-bold text-teal" to="/teacher/forgot-password">Request a new link</Link></section>
  return <section className="mx-auto max-w-lg rounded-2xl bg-white p-8"><h1 className="text-3xl font-extrabold">Choose a new password</h1><form onSubmit={submit} className="mt-6 space-y-4" aria-busy={pending}><label className="block font-bold">New password<input required type="password" autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border-2 p-3" /></label><label className="block font-bold">Confirm new password<input required type="password" autoComplete="new-password" value={confirm} onChange={e => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border-2 p-3" /></label>{message && <p role={message.startsWith('Your') ? 'status' : 'alert'}>{message}</p>}<button disabled={pending} className="rounded-xl bg-teal px-5 py-3 font-bold text-white disabled:opacity-60">{pending ? 'Updating…' : 'Update Password'}</button></form><SignOutButton /></section>
}
