import { FormEvent, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { authErrorMessage, withAuthTimeout } from '../lib/authHelpers'
import { getSupabaseSetupMessage, supabase, supabaseConfigured } from '../lib/supabase'
export default function TeacherForgotPasswordPage() {
  const [email, setEmail] = useState(''); const [pending, setPending] = useState(false); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const locked = useRef(false)
  async function submit(event: FormEvent) { event.preventDefault(); if (locked.current) return; if (!supabaseConfigured || !supabase) { setError(getSupabaseSetupMessage()); return }; locked.current = true; setPending(true); setError(''); try { const result = await withAuthTimeout(supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: `${window.location.origin}/teacher/reset-password` })); if (result.error) setError(authErrorMessage(result.error)); else setSent(true) } catch (failure) { setError(authErrorMessage(failure)) } finally { locked.current = false; setPending(false) } }
  return <section className="mx-auto w-full max-w-md rounded-[2rem] bg-white p-7 shadow-xl sm:p-10"><h1 className="text-3xl font-extrabold text-ink">Forgot your password?</h1>{sent ? <p className="mt-4" role="status">If an account exists for that email, you’ll receive a password reset link.</p> : <form onSubmit={submit} className="mt-7 space-y-5" aria-busy={pending}><label className="block font-bold text-ink">Email<input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border-2 border-[#d9e3e2] px-4 py-3 text-base" /></label>{error && <p role="alert">{error}</p>}<button disabled={pending} className="min-h-14 w-full rounded-xl bg-teal px-5 py-3.5 font-extrabold text-white disabled:opacity-60">{pending ? 'Sending…' : 'Send Reset Link'}</button></form>}<Link className="mt-6 inline-block font-bold text-teal" to="/teacher/login">Back to Sign In</Link></section>
}
